<?php
/******************************************
French
Admin Category Language
******************************************/

$lang['categories']					= 'Catégories';
$lang['error_must_select']			= 'Vous devez sélectionner une catégorie.';
$lang['error_not_found']			= 'La catégorie demandé n\'a pas été trouvée';
$lang['organize_category']			= 'Organiser la catégorie "%s"';
$lang['organize']					= 'Organiser';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Catégorie';
$lang['name']						= 'Nom';
$lang['slug']						= 'Slug';
$lang['description']				= 'Description';
$lang['excerpt']					= 'Extrait';
$lang['sequence']					= 'Séquence';
$lang['image']						= 'Image';
$lang['seo_title']					= 'Titre dans le SEO';
$lang['meta']						= 'Métadonnées';
$lang['message_category_saved']		= 'La catégorie a été sauvegardée !';
$lang['error_file_upload']			= '<p>Vous n\'avez pas séléctionné un fichier à uploader.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'La catégorie a été supprimée.';
$lang['current_file']				= 'Fichier en cours';
$lang['confirm_delete_category']	= 'Êtes-vous sûr de vouloir supprimer cette catégorie ?';
$lang['add_new_category']			= 'Ajouter une nouvelle catégorie';
$lang['no_categories']				= 'Il n\'y a actuellement aucune catégorie';
$lang['attributes']					= 'Attributs';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="Ce produit est extraordinaire" /&gt;';
$lang['drag_and_drop']				= 'Glissez-déposer les produits dans l\'ordre où vous souhaitez les voir apparaitre';
$lang['sku']						= 'SKU';
$lang['price']						= 'Prix';
$lang['sale']						= 'Promotion';
$lang['max_file_size']				= 'Taille de fichier maximale';